### ISSUE TITLE
Error: Cross-Site Request Forgery

### ISSUE THREAD

**Issue by Gianniballerini** [macfanatic/SprintApp#47]
The version of Devise being used contains a flaw that allows a remote, user-assisted attacker to conduct a CSRF token fixation attack. This issue is triggered as previous CSRF tokens are not properly invalidated when a new token is created. If an attacker has knowledge of said token, a specially crafted request can be made to it, allowing the attacker to conduct CSRF attacks.

**Category description**: Failure to verify that the sender of a web request actually intended to do so.

**Solution**: upgrade devise to ~> 2.2.5 or >= 3.0.1

**Comment by macfanatic** [comment]
Unsupported 4 year old repo, closing.
